# Generated by Django 3.2.4 on 2021-07-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان تگ')),
                ('slug', models.SlugField(max_length=150, verbose_name='آدرس تگ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
            ],
        ),
    ]
