# Generated by Django 4.1.1 on 2022-09-07 10:44

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='متن')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'ویرایش درباره ما',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_logo', models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='تصویر لوگوی هدر')),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='تصویر لوگوی فوتر')),
                ('fav_logo', models.ImageField(blank=True, null=True, upload_to='images/logo', verbose_name='لوگوی نوبار')),
                ('office_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس دفتر')),
                ('office_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن دفتر')),
                ('office_fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره فکس دفتر')),
                ('office_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل دفتر')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
